Feat/add information button
molgenis/molgenis-ui-form pull request #390
Opened 2022-01-13 10:23 UTC by MaxPostema

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] No warnings during install
- [ ] Updated flow typing

2022-01-18 14:30 UTC, chinook25 approved these changes

2022-01-20 15:08 UTC, jelmerveen requested changes

2022-01-20 15:08 UTC, jelmerveen commented on src/components/DescriptionUrls.vue
> +          return [...accumulator, { text: current, url: split[index + 1] }]
what is in the accumulator

2022-01-20 15:08 UTC, jelmerveen commented on src/components/DescriptionUrls.vue
> +        return 'https://' + url
what does this actually do? only check for protocol? then you could better check this regex: /^http/gmi

2022-01-20 15:08 UTC, jelmerveen commented on test/unit/specs/field-types/MultiSelectFieldComponent.spec.js
> +      stubs: { fieldMessages: '<div>This field is required</div>' }
you could declare fieldMessages as a constant, and then only add the property like:

```const fieldMessages = '<div>This field is required</div>'```


```stubs: { fieldMessages }```

Saves a lot of copy paste

2022-01-21 09:13 UTC, chinook25 commented on src/components/Description.vue
> +  return $t &&
If it exists and the values are not set, it should use default values, thus the function returns false. At least that is what I understand from this code :)

2022-01-21 09:47 UTC, jelmerveen approved these changes

2022-01-25 13:01 UTC, merged